# Generated by Django 4.2.3 on 2023-07-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_remove_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='asdasdasd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
